[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    authorization: Marker for authorization tests
    smoke: Marker for smoke tests
    slow: Marker for slow tests
    dashboard: Marker for dashboard tests
    integration: Marker for integration tests
    login: Marker for login tests
    unit: Marker for unit tests
    regression: Marker for regression tests
    registration: Marker for registration tests
    courses: Marker for courses tests


